### PR TITLE
Add the systemd service to PKGBUILD

### PR DESCRIPTION
**Pull request by He-Ro**
This is just a small update to the PKGBUILD.
I was wondering why grobi was not in the AUR.
Would you mind, if I uploaded this PKGBUILD to the AUR?

### CODE REVIEW

**Comment by fd0** [comment]
Not at all, please do so! If you like, you can add me as a co-maintainer, I'm `fd0` on AUR.

**Comment by He-Ro** [comment]
Added it: https://aur.archlinux.org/packages/grobi-git/

**Comment by fd0** [comment]
Cool. Can we drop the `PKGBUILD` from this repo? I think it's sufficiently managed in the AUR git...

**Comment by He-Ro** [comment]
Definitely

**Comment by fd0** [comment]
Done.

**Pull request merged**
